#!/usr/bin/perl -w
#
# coccicheck
#       A more generic coccinelle wrapper but following the same idea from the Linux version.
use strict;

my $nrproc = `getconf _NPROCESSORS_ONLN`;
chomp($nrproc);
my $macros = $0;
$macros =~ s,/[^/]+$,/macros,;

my $srcdir;
if ($ARGV[0] !~ /\.cocci$/) {
   $srcdir = $ARGV[0];
} else {
   $srcdir = $ARGV[1];
}
$srcdir =~ s,/\K[^/]+$,, if (! -d $srcdir);
$srcdir = `cd '$srcdir' && git rev-parse --show-toplevel`;
chomp($srcdir);

my @cocci = grep(/\.cocci$/, @ARGV);
my $optstr = `grep -P '^\\s*//\\s*Options:' '$cocci[0]' | cut -d: -f2`;
$optstr =~ s/^\s+//;
$optstr =~ s/\s+$//;
my @opts = split(/\s+/, $optstr);

system('spatch', '--macro-file', $macros, '-j', $nrproc, '--patch', $srcdir, '--quiet', @opts, @ARGV);
